name: Build Clone PL

on:
  push:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true
  snow_user: ${{ secrets.SNOW_USER }}
  snow_pwd: ${{ secrets.SNOW_PASSWORD }}
  snow_acc: ${{ secrets.SNOW_ACCOUNT }}

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - "3.10"
    name: Test
    runs-on: ${{ matrix.os }}

    inputs:
      db_name:
        description: 'Database Name'
        required: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest -v

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated logs" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
